Metrics app Milestone 4
ambrose-kibet/metrics-webapp pull request #1
Opened 2023-03-22 15:00 UTC by ambrose-kibet

## In this milestone we:
- [ ] Used redux to fetch and persist data from the api
- [ ] Created the UI for the metrics app.
- [ ] Added test for the metrics app

2023-03-22 16:36 UTC, Ismailco requested changes
#### Hi @ambrose-kibet, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
You did a great job, keep up the good work 👍🏼

![giphy](https://user-images.githubusercontent.com/25227022/169391888-8dd8108f-0d42-4e54-87cc-a3f9fd392dbc.gif)


## Highlights

✔️ Clean code
✔️ Implement testing
✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-22 16:36 UTC, Ismailco commented on src/pages/Homepage.js
> +          <SingleCurrency
- [ ] The list of coins in the `Home page` can be filtered using given parameters (like the name of the coin for example), kindly make sure to add a search area on the home page that can filter the list of coins and display only relevant ones when searching

2023-03-22 16:36 UTC, Ismailco commented on src/pages/Homepage.js
> +    <section className="section-container">
- [ ] Kindly make sure to follow the provided design, you can use the `opacity` property to add a different color shad for every second column on the Home page or just add two different shades of the same color to style the coins cards

|Your app|Provided design|
|-|-|
|![Screenshot_20230322_163017](https://user-images.githubusercontent.com/25227022/226973187-5a87ce29-9282-4780-8ed9-5866b8d7e3cc.png)|![Screenshot_20230322_163141](https://user-images.githubusercontent.com/25227022/226973631-feb8a27e-2bbd-4286-9f56-002d91357c54.png)|

2023-03-22 16:36 UTC, Ismailco commented on src/pages/DetailsPage.js
> +        </div>
- [ ] Same here, kindly make sure to follow the provided design, you can use the `opacity` property to add a different color shad for every second column on the Detail page or just add two different shades of the same color to style the information rows

|Your app|Provide design|
|-|-|
|![Screenshot_20230322_163419](https://user-images.githubusercontent.com/25227022/226974244-46b518a1-400b-4ad7-86bb-9291bf787af6.png)|![Screenshot_20230322_163152](https://user-images.githubusercontent.com/25227022/226974133-9993b30a-a0e5-42d9-8af3-5face54e0a80.png)|

2023-03-23 06:35 UTC, mwanawabangona approved these changes
Hi @ambrose-kibet 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 06:39 UTC, merged

2023-03-27 08:00 UTC, amejid reviewed
Hi @ambrose-kibet, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/RltjLEzzB87ErJdxHz/giphy.gif"/>

## Highlights
- Good test coverage :heavy_check_mark: 
- Functionalities working as expected :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._